cas:
  authn:
    accept:
      users: ""
    jdbc:
      query:
        - driver-class: org.postgresql.Driver
          url: jdbc:postgresql://localhost:5434/cas_db
          user: cas_user
          password: cas_password
          sql: "SELECT password FROM users WHERE username = ? and enabled = true"
          field-password: password
          password-encoder:
            type: BCRYPT
    attribute-repository:
      jdbc:
        - id: userattrs
          order: 0
          driver-class: org.postgresql.Driver
          url: jdbc:postgresql://localhost:5434/cas_db
          user: cas_user
          password: cas_password
          sql: "SELECT attribute_value as groupMembership FROM user_attributes WHERE username = ? AND attribute_name = 'groupMembership'"
          username: username
          attributes:
            groupMembership: groupMembership
          singleRow: true
          requireAllAttributes: false
  jdbc:
    show-sql: true
  service-registry:
    core:
      init-from-json: true
    json:
      location: classpath:/etc/cas/services
  server:
    name: https://localhost:8080
    prefix: https://localhost:8080/cas
  webflow:
    crypto:
      enabled: false
  tgc:
    crypto:
      enabled: false

server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:thekeystore
    key-store-password: changeit
    key-alias: cas

logging:
  level:
    org:
      apereo:
        cas: DEBUG
      springframework:
        jdbc: DEBUG
    root: WARN