cas:
  authn:
    accept:
      users: ""
    jdbc:
      query:
        - driver-class: org.postgresql.Driver
          url: jdbc:postgresql://localhost:5434/cas_db
          user: cas_user
          password: cas_password
          sql: "SELECT password FROM users WHERE username = ? and enabled = true"
          field-password: password
          password-encoder:
            type: BCRYPT
    attribute-repository:
      jdbc:
        - id: userattrs
          order: 0
          driver-class: org.postgresql.Driver
          url: jdbc:postgresql://localhost:5434/cas_db
          user: cas_user
          password: cas_password
          sql: "SELECT attribute_value as groupMembership FROM user_attributes WHERE username = ? AND attribute_name = 'groupMembership'"
          username: username
          attributes:
            groupMembership: groupMembership
          singleRow: true
          requireAllAttributes: false
    oidc:
      core:
        issuer: https://localhost:8080/cas/oidc
      jwks:
        file-system:
          jwks-file: file:etc/cas/keystore.jwks
    saml-idp:
      core:
        entity-id: https://localhost:8080/idp
      metadata:
        file-system:
          location: file:etc/cas/saml
  #  account-registration:
#    core:
#      security-questions-count: 0
#      crypto:
#        enabled: false
#    mail:
#      attribute-name: "email"
#      from: "ieltsonlinetest67@gmail.com"
#      subject: "Activate your account"
#    provisioning:
#      groovy:
#        location: file:/etc/cas/scripts/register.groovy
  jdbc:
    show-sql: true
  service-registry:
    core:
      init-from-json: true
    json:
      location: classpath:/etc/cas/services
  server:
    name: https://localhost:8080
    prefix: https://localhost:8080/cas
  webflow:
    crypto:
      enabled: false
  tgc:
    crypto:
      enabled: false

server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:thekeystore
    key-store-password: changeit
    key-alias: cas

logging:
  level:
    org:
      apereo:
        cas: DEBUG
      springframework:
        jdbc: DEBUG
    root: WARN

#spring:
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ieltsonlinetest67@gmail.com
#    password: ppzopbjeqwdkximo
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true